In [219]:
# Importing the libraries
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
from pandas import Series
from collections import defaultdict
from sklearn.preprocessing import LabelEncoder
import datetime
import calendar

# Importing the dataset
df = pd.read_csv('test.txt', sep="\t", error_bad_lines=False)
s = df['item_type'].str.split(',').apply(Series, 1).stack()
s.index = s.index.droplevel(-1)
s.name = 'item_type'
del df['item_type']
df = df.join(s)
df['item_type'] = df['item_type'].apply(lambda x: x.split('_')[-1].replace('\'','').replace(']',''))
df = df[df['item_type']!='null'].reset_index()
del df['index']
del df['role_id']
del df['rk']


df['t_when'] = df['t_when'].apply(lambda x: calendar.timegm(datetime.datetime.strptime(x, "%Y-%m-%d %H:%M:%S").utctimetuple())) 

d = defaultdict(LabelEncoder)
pd.Categorical(df['app_channel'])
pd.Categorical(df['item_type'])

le = LabelEncoder()
fit = df.apply(lambda x: d[x.name].fit_transform(x) if (x.name == ('item_type')) else x)
df = df.apply(lambda x: d[x.name].fit_transform(x) if (x.name in ('item_type', 'app_channel')) else x )
df

,t_when,role_level,item_price,role_force,crystal,gold,state,app_channel,item_type
0,1500021518,45,1.0,16157.0,0,152801,1,0,7
1,1500021518,45,1.0,16157.0,0,152801,1,0,0
2,1500051969,45,2.0,16157.0,0,153465,1,0,6
3,1500051969,45,2.0,16157.0,0,153465,1,0,0
4,1500471171,45,3.0,16972.0,0,157408,1,0,0
5,1500471171,45,3.0,16972.0,0,157408,1,0,6
6,1500101064,45,3.0,16198.0,0,155568,1,0,1
7,1500101064,45,3.0,16198.0,0,155568,1,0,0
8,1500105566,45,4.0,16198.0,0,155568,1,0,2
9,1500105566,45,4.0,16198.0,0,155568,1,0,3
10,1500045606,45,1.0,20672.0,0,21630,1,0,6
11,1500045606,45,1.0,20672.0,0,21630,1,0,0
12,1500024112,45,2.0,20470.0,0,20297,1,0,0
13,1500024112,45,2.0,20470.0,0,20297,1,0,7
14,1500038830,45,2.0,20470.0,0,21630,1,0,7
15,1500038830,45,2.0,20470.0,0,21630,1,0,1
16,1500028615,45,3.0,20470.0,0,20297,1,0,0
17,1500028615,45,3.0,20470.0,0,20297,1,0,6
18,1500111226,45,2.0,20991.0,0,21630,1,0,6
19,1500111226,45,2.0,20991.0,0,21630,1,0,4
20,1500543697,45,2.0,21076.0,0,22815,1,0,7
21,1500543697,45,2.0,21076.0,0,22815,1,0,0
22,1500211552,45,3.0,21076.0,0,22815,1,0,0
23,1500211552,45,3.0,21076.0,0,22815,1,0,1
24,1500129869,45,3.0,21076.0,0,22815,1,0,1
25,1500129869,45,3.0,21076.0,0,22815,1,0,4
26,1500194812,45,4.0,21076.0,0,22815,1,0,2
27,1500194812,45,4.0,21076.0,0,22815,1,0,6
28,1500558348,45,2.0,21076.0,0,22940,1,0,1
29,1500558348,45,2.0,21076.0,0,22940,1,0,4
...,...,...,...,...,...,...,...,...,...
5739,1500334806,45,2.0,23663.0,0,7517,1,2,6
5740,1500334806,45,2.0,23663.0,0,7517,1,2,7
5741,1500328734,45,3.0,23663.0,0,4481,1,2,4
5742,1500328734,45,3.0,23663.0,0,4481,1,2,0
5743,1500229616,45,1.0,23982.0,0,54991,1,2,6
5744,1500229616,45,1.0,23982.0,0,54991,1,2,1
5745,1500266588,45,1.0,24331.0,0,61297,1,2,7
5746,1500266588,45,1.0,24331.0,0,61297,1,2,6
5747,1500247010,45,2.0,24142.0,0,55249,1,2,1
5748,1500247010,45,2.0,24142.0,0,55249,1,2,0
5749,1500260363,45,2.0,24247.0,0,58583,1,2,4
5750,1500260363,45,2.0,24247.0,0,58583,1,2,7
5751,1500252588,45,3.0,24247.0,0,58085,1,2,2
5752,1500252588,45,3.0,24247.0,0,58085,1,2,0
5753,1500133673,45,1.0,23414.0,0,46352,1,2,0
5754,1500133673,45,1.0,23414.0,0,46352,1,2,7
5755,1500167797,45,1.0,23723.0,0,50502,1,2,1
5756,1500167797,45,1.0,23723.0,0,50502,1,2,5
5757,1500144843,45,2.0,23414.0,0,46352,1,2,4
5758,1500144843,45,2.0,23414.0,0,46352,1,2,6
5759,1500164495,45,2.0,23723.0,0,50502,1,2,6
5760,1500164495,45,2.0,23723.0,0,50502,1,2,0
5761,1500155448,45,3.0,23607.0,0,50224,1,2,4
5762,1500155448,45,3.0,23607.0,0,50224,1,2,1
5763,1500291070,45,2.0,24395.0,0,61297,1,2,6
5764,1500291070,45,2.0,24395.0,0,61297,1,2,0
5765,1500406485,45,2.0,24443.0,2,21027,1,2,7
5766,1500406485,45,2.0,24443.0,2,21027,1,2,1
5767,1500360872,45,3.0,24443.0,2,20927,1,2,0
5768,1500360872,45,3.0,24443.0,2,20927,1,2,6